# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform:ios, "8.3"
target 'LZSDWebImagePro' do
pod 'SDWebImage', '~>3.7'
end

target 'LZSDWebImageProTests' do

end

